# NumPy Arrays Notebook

## This is a notebook for prectising NumPy Arrays

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.13.3


In [4]:
my_list = list(range(1, 6, 1))

In [5]:
print(my_list)

[1, 2, 3, 4, 5]


In [6]:
array_from_list = np.array(my_list)

In [7]:
array_from_list

array([1, 2, 3, 4, 5])

In [8]:
array_from_list * 10

array([10, 20, 30, 40, 50])

In [9]:
my_tuple = (1, 3.14, 4+5j)
np.array(my_tuple)

array([ 1.00+0.j,  3.14+0.j,  4.00+5.j])

In [10]:
my_tuple * 6

(1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j))

In [11]:
np.array(my_tuple) * 6

array([  6.00 +0.j,  18.84 +0.j,  24.00+30.j])

# Intrinsic NumPy Arrays creation using NumPy Methods

In [12]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
np.arange(10, 50) - 10+ 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [15]:
len(np.arange(10, 25))

15

In [16]:
numpy_range_array = np.arange(10, 25)
numpy_range_array.size

15

In [17]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [18]:
np.arange(26, step = 4)

array([ 0,  4,  8, 12, 16, 20, 24])

# More NumPy Methods

In [19]:
np.linspace(5, 15, 9)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [20]:
np.linspace(0, 100, 10, retstep = True)

(array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
          44.44444444,   55.55555556,   66.66666667,   77.77777778,
          88.88888889,  100.        ]), 11.111111111111111)

# Zeros() Demo

In [21]:
np.zeros(20)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

# Ones() Demo

In [22]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.zeros((5, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
np.zeros((3, 4, 6))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]])

# Data Types Demo

In [25]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.ones(10, dtype = bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [27]:
np.ones(10, dtype = 'int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.ones(10, dtype = complex)

array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,
        1.+0.j,  1.+0.j,  1.+0.j])

# Index Slice and Iterate

In [29]:
my_vector = np.array([-17, 5, 6, 7, 8, 9])

In [30]:
my_vector[4]

8

In [31]:
my_vector[4] = 144

In [32]:
my_vector[4]

144

In [33]:
my_vector[-3]

7

In [34]:
my_vector[305 % 6]

9

In [35]:
my_vector

array([-17,   5,   6,   7, 144,   9])

In [36]:
my_vector.size

6

In [37]:
my_vector[305 % my_vector.size]

9

In [38]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [39]:
my_array[3]

array([15, 16, 17, 18, 19])

In [40]:
my_array[-5]

array([10, 11, 12, 13, 14])

In [41]:
my_array[-4, -3]

17