# NumPy Notebook

## This is a notebook for NumPy important concepts and examples

### Comprehensive NumPy Tutorial is available at https://docs.scipy.org/doc/numpy/user/quickstart.html

In [53]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
print(np.__version__)

1.15.1


In [51]:
my_list = list(range( 1, 10, 2))

In [52]:
print(my_list)

[1, 3, 5, 7, 9]


In [57]:
my_list.append(5)

In [58]:
array_from_list = np.array(my_list)

In [59]:
array_from_list

array([1, 3, 5, 7, 9, 5])

In [60]:
arr = array_from_list / 3

In [61]:
arr, array_from_list

(array([0.33333333, 1.        , 1.66666667, 2.33333333, 3.        ,
        1.66666667]), array([1, 3, 5, 7, 9, 5]))

In [10]:
my_tuple = (1, 3.14, 4+5j)
np.array(my_tuple)

array([1.  +0.j, 3.14+0.j, 4.  +5.j])

In [11]:
my_tuple * 6

(1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j),
 1,
 3.14,
 (4+5j))

In [62]:
tup = (5, 6)
tup * 5 

(5, 6, 5, 6, 5, 6, 5, 6, 5, 6)

In [63]:
np.array(my_tuple) * 6

array([ 6.   +0.j, 18.84 +0.j, 24.  +30.j])

# Intrinsic NumPy Arrays creation using NumPy Methods

In [69]:
np.arange?

In [66]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [67]:
np.arange(10, 50) - 10 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [68]:
len(np.arange(10, 25))

15

In [18]:
numpy_range_array = np.arange(10, 25)
numpy_range_array.size

15

In [19]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [20]:
np.arange(26, step = 4)

array([ 0,  4,  8, 12, 16, 20, 24])

# More NumPy Methods

In [21]:
np.linspace?

In [22]:
np.linspace(0, 100, 10, retstep = True)

(array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
         44.44444444,  55.55555556,  66.66666667,  77.77777778,
         88.88888889, 100.        ]), 11.11111111111111)

# Zeros() Demo

In [73]:
np.zeros((20, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# Ones() Demo

In [74]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
arr = np.zeros((3, 4, 6))
arr
arr.reshape((9, 2, 4))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Data Types Demo

In [27]:
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.ones(10, dtype = str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [29]:
np.ones(10, dtype = 'int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.ones(10, dtype = complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

# Index Slice and Iterate

In [79]:
my_vector = np.array([-17, 5, 6, 7, 8, 9])

In [80]:
my_vector[4]

8

In [81]:
my_vector[4] = 144

In [82]:
my_vector[4]

144

In [83]:
my_vector[-3]

7

In [85]:
my_vector[305 % 6] = 1234

In [86]:
my_vector

array([ -17,    5,    6,    7,  144, 1234])

In [38]:
my_vector.size

6

In [39]:
my_vector[305 % my_vector.size]

9

In [40]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [41]:
my_array[3]

array([15, 16, 17, 18, 19])

In [90]:
my_array[5, 2]

27

In [91]:
my_array[-2, -3]

27

In [92]:
my_array[5, -3]

27

In [95]:
first_array = np.array([1, 2, 4])
second_array = np.array([2, 3, 7])

first_array * second_array



array([ 2,  6, 28])

In [96]:
np.dot(first_array, second_array)

36

In [46]:
def decorator_sample (func, operation):
    if operation == 'Add':
        return func;
    
def func(x, y):
    print();


result = decorator_sample(func, 'Add');

In [97]:
def my_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        database_connection()
        print("Something is happening after the function is called.")
    return wrapper

@my_decorator()
def database_connection():
    print("Whee!")

say_whee = my_decorator(database_connection)
say_whee()

TypeError: my_decorator() missing 1 required positional argument: 'func'

In [48]:
np.sum(first_array)

7

In [49]:
first_array.shape

(3,)

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])