# Boolean Mask Arrays

In [1]:
import numpy as np

In [2]:
my_vector = np.arange(8)
my_vector

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
zero_mod_7_mask = 0 == (my_vector % 7)

In [4]:
zero_mod_7_mask

array([ True, False, False, False, False, False, False,  True], dtype=bool)

In [5]:
sub_array = my_vector[zero_mod_7_mask]

In [6]:
sub_array

array([0, 7])

# NumPy Logical Operators

In [7]:
mod_test = 0 == (my_vector % 7)
mod_test

array([ True, False, False, False, False, False, False,  True], dtype=bool)

In [8]:
positive_test = my_vector > 0
positive_test

array([False,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [9]:
combined_mask = np.logical_and(mod_test, positive_test)

In [10]:
combined_mask

array([False, False, False, False, False, False, False,  True], dtype=bool)

In [11]:
my_vector[combined_mask]

array([7])

# Broadcasting

NumPy operations with arrays with different sizes

In [12]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [13]:
# Shape

my_3d_array.shape

(2, 7, 5)

In [14]:
# Number of Dimensions

my_3d_array.ndim

3

In [15]:
# Size

my_3d_array.size

70

In [16]:
# Data Type

my_3d_array.dtype

dtype('int64')

In [17]:
5*my_3d_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [18]:
left_mat = np.arange(6).reshape((2,3))
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
right_mat = np.arange(15).reshape((3,5))
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

# Operating Along Axes

In [21]:
my_3d_array.shape

(2, 7, 5)

In [22]:
my_3d_array.sum()

2415

In [23]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [24]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [25]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

# Broadcasting Rules

In [26]:
my_2d_array = np.ones(35, dtype = int).reshape((7,5)) * 3

In [27]:
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
my_random_2d_array = np.random.random((7, 5))

In [29]:
my_random_2d_array

array([[ 0.37028798,  0.07092597,  0.49236566,  0.71380849,  0.0037811 ],
       [ 0.08439091,  0.25463921,  0.44266424,  0.372178  ,  0.20955002],
       [ 0.4885875 ,  0.46319078,  0.3280604 ,  0.80529952,  0.15833921],
       [ 0.51797708,  0.03158364,  0.24229051,  0.87523211,  0.8782588 ],
       [ 0.32213134,  0.01085179,  0.03188177,  0.92044258,  0.70148503],
       [ 0.29042092,  0.37248626,  0.69990805,  0.4360952 ,  0.75950501],
       [ 0.34294399,  0.28694003,  0.105186  ,  0.99225891,  0.32983694]])

In [30]:
np.set_printoptions(precision = 4)
my_3d_array * my_random_2d_array

array([[[  0.0000e+00,   7.0926e-02,   9.8473e-01,   2.1414e+00,
           1.5124e-02],
        [  4.2195e-01,   1.5278e+00,   3.0986e+00,   2.9774e+00,
           1.8860e+00],
        [  4.8859e+00,   5.0951e+00,   3.9367e+00,   1.0469e+01,
           2.2167e+00],
        [  7.7697e+00,   5.0534e-01,   4.1189e+00,   1.5754e+01,
           1.6687e+01],
        [  6.4426e+00,   2.2789e-01,   7.0140e-01,   2.1170e+01,
           1.6836e+01],
        [  7.2605e+00,   9.6846e+00,   1.8898e+01,   1.2211e+01,
           2.2026e+01],
        [  1.0288e+01,   8.8951e+00,   3.3660e+00,   3.2745e+01,
           1.1214e+01]],

       [[  1.2960e+01,   2.5533e+00,   1.8218e+01,   2.7125e+01,
           1.4746e-01],
        [  3.3756e+00,   1.0440e+01,   1.8592e+01,   1.6004e+01,
           9.2202e+00],
        [  2.1986e+01,   2.1307e+01,   1.5419e+01,   3.8654e+01,
           7.7586e+00],
        [  2.5899e+01,   1.6108e+00,   1.2599e+01,   4.6387e+01,
           4.7426e+01],
        [  1.7717e+

In [31]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [32]:
my_3d_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [33]:
my_3d_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])

# Creating Structured Arrays

In [34]:
person_data_def = [('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [35]:
people_array = np.zeros(4, dtype = person_data_def)
people_array

array([(b'',  0.,  0., 0), (b'',  0.,  0., 0), (b'',  0.,  0., 0),
       (b'',  0.,  0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [36]:
people_array[3] = ('Delta', 73, 205, 34)

In [37]:
people_array[0] = ('Alpha', 65, 112, 23)

In [38]:
people_array

array([(b'Alpha',  65.,  112., 23), (b'',   0.,    0.,  0),
       (b'',   0.,    0.,  0), (b'Delta',  73.,  205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [39]:
people_array[0:]

array([(b'Alpha',  65.,  112., 23), (b'',   0.,    0.,  0),
       (b'',   0.,    0.,  0), (b'Delta',  73.,  205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [40]:
ages = people_array['age']

In [41]:
ages

array([23,  0,  0, 34])

# Multi-Dimensional Structural Arrays

In [42]:
people_big_array = np.zeros((4,3,2), dtype = person_data_def)

In [43]:
people_big_array

array([[[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]],

       [[(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)],
        [(b'',  0.,  0., 0), (b'',  0.,  0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [44]:
people_big_array[3,2,1] = ('Echo', 67, 155, 46)

In [45]:
people_big_array

array([[[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)]],

       [[(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'',   0.,    0.,  0)],
        [(b'',   0.,    0.,  0), (b'Echo',  67.,  155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [46]:
people_big_array['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,  67.]]])

In [47]:
people_big_array[['height', 'weight']]

array([[[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)]],

       [[(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), (  0.,    0.)],
        [(  0.,    0.), ( 67.,  155.)]]],
      dtype=[('height', '<f8'), ('weight', '<f8')])

# Creating Record Array

In [48]:
person_record_array  = np.rec.array([('Donald', 78, 100, 34),('Knuth', 98, 102, 67)], dtype = person_data_def)
person_record_array

rec.array([(b'Donald',  78.,  100., 34), (b'Knuth',  98.,  102., 67)], 
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [49]:
person_record_array[0].age

34

In [50]:
person_record_array[0].height

78.0

In [51]:
person_record_array[0].weight

100.0